spring:
  application:
    name: data-collection
  kafka:
    bootstrap-servers: localhost:9092
    streams:
      application-id: data-collection
      bootstrap-servers: localhost:9092
      properties:
        default-key-serde: org.apache.kafka.common.serialization.Serdes$StringSerde
        default-value-serde: com.engkimbs.serializer.JsonSerde
        schema-registry-url: http://localhost:8081